version: '2'

services:
  app:
    container_name: democracyos-app
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    env_file: docker/.env
    links:
      - mongo
    ports:
      - "3000:3000"
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - /var/www/democracyos:/usr/src
      - /usr/src/node_modules
    tty: true

  mongo:
    image: mongo:3.2
    # Optionally mount external data directory
    # volumes:
    #   - path-to-your-data-dir:/data/db
